### ISSUE TITLE
Hi, may I request the code for your paper on 2020 IROS? Factor Graph based 3D Multi-Object Tracking in Point Clouds

### ISSUE THREAD

**Issue by bill4278** [TUC-ProAut/libRSF#11]
Hi, thanks for your wonderful work presented on the 2020 IROS (DOI: 10.48550/ARXIV.2008.05309). I was trying to implement your algorithm, but I'm not good at understanding all the detailed things in your paper. Can I maybe request a copy of your source code?

**Comment by tipf** [comment]
Thanks for reaching out, but the tracking code is maintained separately from the libRSF.
It will be published in the [FG-3DMOT](https://github.com/TUC-ProAut/FG-3DMOT) repository.
This will include the IV version of the algorithm. ([10.1109/IV48863.2021.9575636](https://doi.org/10.1109/IV48863.2021.9575636))

Best Regards
Tim

**Comment by bill4278** [comment]
Great! Thank you very much.
