### ISSUE TITLE
How do you go about visualizing the results of your experiments?

### ISSUE THREAD

**Issue by mingyang86** [TUC-ProAut/libRSF#15]
Thanks for your work. I'm curious about how you visualize the experimental results, like the GIF animations you showed. Is the software you use available?

**Comment by tipf** [comment]
Sorry for responding so late, but do not actively maintain this repo at the moment.
The GIF was created using the `geoplot `function of Matlab: 
https://de.mathworks.com/help/matlab/ref/geoplot.html

We used this function to add high resolution maps from OpenStreetMaps as background:
https://de.mathworks.com/help/map/ref/addcustombasemap.html
