### ISSUE TITLE
Typo? factor graph based multiple object tracking papers.

### ISSUE THREAD

**Issue by sshhj89** [TUC-ProAut/libRSF#16]
Hi.

I am very interested in your approach using GMM for resilience of object associations and thank you for your repository. 

I would like to ask about the constant velocity factor in the paper 
"Optimization based 3D Multi-Object Tracking using Camera and Radar Data" and "Factor Graph based 3D Multi-Object Tracking in Point Clouds".

How can get the X_pos at time t+1 while constructing and optimizing the factor graph at time t and t-1. 

![image](https://github.com/user-attachments/assets/d5cf3ccc-ec1f-4ad9-a22a-6961abf719fc)

Other error models for rotation and dimension uses constant value factor and its time periods are t and t-1. 

Can you help me understand the constant velocity factor?

Sincerely,
Hojun Son.

**Comment by tipf** [comment]
Hi Hojun, you are right. This must be a typo in equation (7).
The constant velocity model is always applied between the current and the last position.

The code can be found here: https://github.com/TUC-ProAut/libRSF/blob/d54801a232af02c0cda6012dabd3dea6c5fd77c5/include/factors/ConstantDriftFactor.h#L63

Best Regards
Tim
