### ISSUE TITLE
Loss function of Max-Mixture

### ISSUE THREAD

**Issue by MayHarryWang** [TUC-ProAut/libRSF#17]
Hi,

Thanks for releasing the useful library about GMM. I really learned a lot!

However, I have one question when studying your dissertation about the derivation of Max-Mixture.
I'd like to ask how to derive the vector-valued loss function (Eq 3.18) shown in the figure below?

![MM](https://github.com/user-attachments/assets/638da7c7-417e-40e1-b6fc-2f3374ae55af)

I'm wondering why the loss function becomes vector form? Because it seems to be different between the form in Eq 3.8 as shown below.

![image](https://github.com/user-attachments/assets/9f9efdcb-52ed-41ff-a8f0-161b25fac67c)

Could you please explain how to derive the equation? 
Thanks.

Best regards,
Harry

**Comment by tipf** [comment]
Hi Harry,
it is a quite simple trick. For max-mixture, you have to replace the sum() operator in equation (3.8) by a max() operator. Then, you can push the logarithm inside and everything else should follow naturally. (It might be a bit more intuitive if you leave out the square root at the beginning and derive the squared cost.)

Best Regards
Tim

**Comment by MayHarryWang** [comment]
Hi,

Thanks for your explanation!

I understand the function in the logarithm can be pulled out by replacing the max() operator.

I only have last two questions:
Is Eq 3.18 the vector form of Eq 3.8? (both are unsquared loss function)
Will the Eq 3.18 eventually be squared when implementing the Max-Mixture model?
I wonder if the squared loss function becomes $`\Phi(r) * \Phi(r)^T`$?

Best regards,
Harry

**Comment by tipf** [comment]
Lets make an simple example:
The squared cost of Max-Mixture is something like $F = a + b$, where $F = f^Tf$.
Using a NLS solver, requires defining $f$ instead of $F$.
So we have two possibilities, either
```math
f = \sqrt{a + b}\\
```
or
```math
f = \begin{bmatrix} \sqrt{a} \\ \sqrt{b} \end{bmatrix}.
```
Booth variants give you $F = f^Tf = a + b$, but the vectorized version has the more well-behaved Jacobian.
The square-root $f$ will be squared inside the NLS solver -- e.g. ceres.

Best Regards
Tim

**Comment by MayHarryWang** [comment]
Hi,

Thank you very much!

Your explanation is simple and easy to understand.
Also, your dissertation and code is really valuable for me.
I'll keep studying your work and find out what can I do to improve the model.

Best regards,
Harry
