### ISSUE TITLE
matlab in windows X86

### ISSUE THREAD

**Issue by liqiumei-bjtu** [TUC-ProAut/libRSF#7]
Hello, author. First of all, thank you very much for your work. I have encountered some problems in the process of using it. I hope you can give me some suggestions. When I tried to run the program in matlab file using windows x64, an error occurred. ”Did not find build directory for libRSF binary! “ How can I solve this problem? Thank you again!

**Comment by tipf** [comment]
Hi and thanks for your interest!
At first, I have to say that we can't support windows fully, since we have no windows machines here.

However, I tried to make the Matlab interface more flexible by using generic path separators. Please report back if this solves your problem.
